# Generated by Django 6.0.4 on 2026-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-solid fa-building', help_text='Font Awesome class for the company icon', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Font Awesome class, e.g. "fa-brands fa-python"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_me',
            field=models.TextField(blank=True, help_text='Paragraph text for the About section.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cv_link',
            field=models.URLField(blank=True, help_text='Link to Google Drive containing your CV'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_description',
            field=models.TextField(default='Transforming data into intelligent solutions through Machine Learning, AI, and advanced analytics.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='name',
            field=models.CharField(default='Moataz Nageh Saber', max_length=200),
        ),
    ]
