# Generated by Django 6.0.4 on 2026-04-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_experience_skill_remove_siteconfig_cv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(default='Portfolio of Moataz Nageh Saber — AI Engineer, and Data Analyst.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_title',
            field=models.CharField(default='Moataz Nageh Saber | AI Engineer Portfolio', max_length=200),
        ),
    ]
