# Generated by Django 6.0.4 on 2026-04-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_siteconfig_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='universities/'),
        ),
    ]
